version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "helm"
    directory: "charts/"
    schedule:
      interval: "monthly"
